theme: jekyll-theme-tactile
title: "The Philosophy of Domhan Dubh"
description: This is a community for the study and development of the Domhan Dubh philosophy.

exclude:
  - Security.md
  - Readme.md
